2020-02-20 13:12:26,670 ERROR: Exception on /edit [POST] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: employee.employeeid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 164, in edit
    db.session.commit()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1136, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1095, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: employee.employeeid
[SQL: INSERT INTO employee (employeeid, name, email, "ProductGroup", "Level2", "Level3", "RTStart", "SectorRank", "SectorRanknew", "SectorRankfinal", "Comments") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('74235', None, None, None, None, None, None, None, 'SR70', None, 'testing testing test')]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-02-22 08:44:18,989 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-22 08:54:35,614 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-22 13:17:08,736 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
2020-02-22 13:25:48,522 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
2020-02-27 06:31:37,103 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
2020-02-28 14:11:00,885 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
2020-02-28 14:18:12,644 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
2020-02-28 14:25:18,066 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:75]
